name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'  # Use your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Make sure this matches your build command

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs after the build job

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this path based on your build output
